---
book_repo: pivotal-cf/docs-book-ipsec
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: edge
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: ipsec/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-addon-ipsec
    ref: 'master'
  directory: addon-ipsec/1-n
  subnav_template: addon_ipsec_1-n.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    changelog_href: https://docs.pivotal.io/addon-ipsec/1-n/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: IPsec
    search_placeholder: Search IPsec 1.10
    url_prefix: addon-ipsec/1-n
    local_product_version: 1.10
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-ipsec/1-9
        display_name: 1.9
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.8.pdf">1.8 (PDF)</a>
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.7.pdf">1.7 (PDF)</a>
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.6.pdf">1.6 (PDF)</a>
      - <a href="http://docs.pivotal.io/archives/addon-ipsec-1.5.pdf">1.5 (PDF)</a>
